### ISSUE TITLE
Implemented unreleased puzzles into new iOS app

### ISSUE THREAD

**Issue by KyleDSwarner** [x-sheep/puzzles-unreleased#7]
Hey there,

I've written a new version of the iOS app for Simon Tatham puzzles, and I implemented the puzzles that you have in your repo into the app that I recently released. I've been playing a lot of Ascent which is quite lovely! 

https://github.com/KyleDSwarner/puzzles-reloaded

https://apps.apple.com/us/app/puzzles-reloaded/id6504365885

My app is MIT licensed and free to play forever - I'd love your feedback if you're an iOS user!

Everything is released & works great, but since these puzzles are your work I'd like to give you right of refusal if you would rather not have them released. If you're okay with it, I'll ensure your name is added to the app as the author of the puzzles.

Cheers!

**Comment by x-sheep** [comment]
Ooh, interesting. I have a MacBook from work, but I don't actually have an iPhone or iPad, so I compiled it locally.

I'm okay with the unreleased puzzles being part of the app, but my main complaint is that there is no License screen anywhere in the app (which the MIT License requires to be compliant).

If you can add a button to the Settings ViewController that displays the license from the upstream project, that would be great. There's no need to add the puzzles-unreleased license separately, since all the contributors in this project have already contributed to the primary repository (in fact, the license here is an older copy of the upstream license)

**Comment by KyleDSwarner** [comment]
Happy to! Adding license & author info page is on my shortlist, I’ll be sure to make sure it’s all in there!

I also have a todo to get this compiling and working on Mac’s and uploaded to the Mac store, so hopefully you’ll be able to try it out that way too.
